version: "3.9"

services:
  web:
    build: ./web
    environment:
      DATABASE_URL: postgresql://ITadmin:yourpassword@flask-db.cnuocu8suj74.eu-west-1.rds.amazonaws.com:5432/flask_db
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: production
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:stable-alpine
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/templates:/usr/share/nginx/html:ro
    ports:
      - "80:80"
